### ISSUE TITLE
Missing icons in application list

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/flathub.org#16]
Some of the applications listed here [0] are missing an icon. Is this due to a specific icon size not being available? In that case, using another icons size would be preferable.

[0] https://www.flathub.org/apps.html

**Comment by TingPing** [comment]
It is because they are proprietary. Except for Scratch that is probably a package bug.

**Comment by Alexander-Wilms** [comment]
Perhaps a generic Flatpak icon could be shown instead.

And Scratch's icon comes from the runtime, so it works correctly when it's installed. In order to be shown on the Flathub website, this [0] issue needs to be resolved.

https://github.com/flatpak/flatpak/issues/842

**Comment by TingPing** [comment]
If we get some third party hosting solution for icons we can't ship they could be referenced by the site too.

**Comment by ramcq** [comment]
We can actually host these icons now. Patches welcome.

**Comment by nedrichards** [comment]
https://github.com/flathub/com.albiononline.AlbionOnline/issues/3 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.armagetronad.ArmagetronAdvanced/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/net.sourceforge.atanks/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.wesnoth.Wesnoth/issues/1 - this is one that just needs a 128px icon

**Comment by nedrichards** [comment]
https://github.com/flathub/net.sourceforge.btanks/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/net.blockout.BlockOutII/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/com.github.babluboy.bookworm/issues/3 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/net.sourceforge.chromium-bsu/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
The discord icon requires remote icons support - this will be added.

**Comment by nedrichards** [comment]
https://github.com/flathub/org.develz.Crawl/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
Exodus needs remote icon support as well.

**Comment by nedrichards** [comment]
https://github.com/flathub/io.github.Freedoom-Phase-1/issues/1
https://github.com/flathub/io.github.Freedoom-Phase-2/issues/2
Freedom changes required.

**Comment by nedrichards** [comment]
https://github.com/flathub/org.frozen_bubble.frozen-bubble/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.gnome.Calculator/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.gnome.Dictionary/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.gnome.Hitori/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.megaglest.MegaGlest/issues/2 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
Skype, Spotify, Slack, RuneScape need remote icon support https://github.com/jgarciao/linux-store-frontend/issues/36

**Comment by nedrichards** [comment]
https://github.com/flathub/net.sourceforge.Ri-li/issues/2 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/im.riot.Riot/issues/5 - another 96x96 only app

**Comment by nedrichards** [comment]
VS Code and Viber need remote icons

**Comment by nedrichards** [comment]
https://github.com/flathub/org.supertuxproject.SuperTux/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/net.sourceforge.torcs/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/com.tux4kids.tuxtype/issues/1 is one of the changes required to fix this issue

**Comment by nedrichards** [comment]
https://github.com/flathub/org.tuxfamily.XMoto/issues/1 is one of the changes required to fix this issue

**Comment by evfool** [comment]
gnome-calculator does not have an icon on flathub, but it has the same icon sizes distributed as gedit, which in turn has an icon on flathub (without having any special icon in the flathub git repo, only the json, and neither 64x64 nor 128x128 icon distributed). I would be ok with distributing 64x64 or 128x128, but would love to find out why this is required by some apps only.

**Comment by evfool** [comment]
FYI, answering my previous question: the name of the app icon calculator distributed is not the same as the id of the flatpak, and the json manifest didn't contain a rename-icon command (which gedit did). After adding that, flatpak-builder did generate the 64x64 and the 128x128 icon (probably as a resize of a larger icon), so I guess it will solve the problem.

**Comment by jimmac** [comment]
The new layout doesn't expose all apps anymore, only curated picks.
