### ISSUE TITLE
PCSX2 missing in Applications

### ISSUE THREAD

**Issue by frantisekz** [flathub/flathub.org#18]
This one is missing on the website: https://github.com/flathub/net.pcsx2.PCSX2

.flatpakref is there and works just fine: https://flathub.org/repo/appstream/net.pcsx2.PCSX2

**Comment by TingPing** [comment]
Because its 32bit only I believe.

**Comment by frantisekz** [comment]
Yep, I didn't notice that, is there any way to install x86 flatpak to x86_64 OS?

**Comment by TingPing** [comment]
They "just work" on 64bit machines (as you said installing the flatpakref worked). The way the website is generated just doesn't take into account other arches.

**Comment by frantisekz** [comment]
Yeah, I forgot I've used --arch=i386 for the first time :smile:
