### ISSUE TITLE
Tremulous has bad icon on the apps page

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/flathub.org#19]
There is only a black background instead of the actual icon for [Tremulous](https://github.com/flathub/com.grangerhub.Tremulous) on the Applications page. I am not sure what causes the issue, the [actual icon](https://flathub.org/repo/appstream/x86_64/icons/64x64/com.grangerhub.Tremulous.png) seems to be correct.

**Comment by danigm** [comment]
I've the same issue with Fractal and I don't know why. Here's the appdata and the icons installed: https://gitlab.gnome.org/danigm/fractal/tree/master/fractal-gtk/res

**Comment by danigm** [comment]
In software app the app is shown with the icon, but the screenshot is an old one.

![captura de pantalla de 2017-12-26 23-41-08](https://user-images.githubusercontent.com/50350/34366026-a5bda2da-ea96-11e7-80be-202a0ecf6155.png)

**Comment by nedrichards** [comment]
Fractal icon is fixed in the new beta app. https://beta.flathub.org/apps

Tremulous is not - I think partly because there isn't a 128x128 icon but there's something else going on there since the icon seems to display in the dev inspector.

**Comment by ramcq** [comment]
CC @jgarciao

**Comment by jgarciao** [comment]
Since this morning the app list uses responsive images: depending on the screen size it will load 64x64 (max-width: 599px) or 128x128 (greater)

https://flathub.org/repo/appstream/x86_64/icons/64x64/com.grangerhub.Tremulous.png
MISSING: https://flathub.org/repo/appstream/x86_64/icons/128x128/com.grangerhub.Tremulous.png

https://github.com/jgarciao/linux-store-frontend/commit/7d84517111de400537121c284df7340e8e1b15c8#diff-aa2d537a9bb6a5403e9b7f9c86f26546R36

**Comment by ramcq** [comment]
Can we also limit the icon selection based on what icons are available? Given we have some apps with 64x64 only and some with 128x128 only. Scaling icons is preferable to missing icons I think.

**Comment by nedrichards** [comment]
We also have some apps that have 96x96px icons or 256x256px icons only, it seems. e.g. https://github.com/flathub/com.remarkable.reMarkable/issues/1

**Comment by jgarciao** [comment]
The icons are placed in the webserver by buildbot or some kind of script (@ramcq might know). I think only 64x64 and 128x128 are imported
- NOT FOUND https://beta.flathub.org/repo/appstream/x86_64/icons/96x96/com.remarkable.reMarkable
- NOT FOUND  https://beta.flathub.org/repo/appstream/x86_64/icons/256x256/com.remarkable.reMarkable

**Comment by jimmac** [comment]
As the current website doesn't expose all apps, I'd close this here and continue the icon scaling discussion on the linux-store-frontend side.
