### ISSUE TITLE
Flatpak Applications page lacks "instructions for how to try them"

### ISSUE THREAD

**Issue by skierpage** [flathub/flathub.org#24]
https://flathub.org/apps.html says
> This page lists some of the apps that are available as Flatpaks, along with instructions for how to try them. ...

but while you're on the "Click to Download" tab there are no instructions. Every app's tile is just a link to its `.flatpakref` file. On Fedora 27 KDE spin, clicking it in Chromium just opens it in my text editor, and Firefox asks if I want to open it in my text editor.

I suggest this tab should say something like
>This page lists some of the apps that are available as Flatpaks. Clicking one should install it if you have the GNOME Software application installed, see [Using Flathub](https://flathub.org/index.html#using) for more details. ...

I noticed the https://flatpak.org/apps.html page has different text in its "Click to Download" tab:
> Click to download is available with Fedora 25 (and newer), Mageia 6 (and newer), OpenSUSE Tumbleweed, Debian 9 (and newer), and Arch, using GNOME Software. Some applications require version 3.22.6 or later.

(version 3.22.6 of what?). They should probably be consistent.

**Comment by TingPing** [comment]
This will happen with the new store: http://45.55.104.129/apps/details/com.play0ad.zeroad

**Comment by allanday** [comment]
> Every app's tile is just a link to its .flatpakref file. On Fedora 27 KDE spin, clicking it in Chromium just opens it in my text editor, and Firefox asks if I want to open it in my text editor.

I've been working on some [design updates for the websites](https://raw.githubusercontent.com/flatpak-design-team/flatpak-website-mockups/master/flathub-wires.png). It would be good to have some feedback whether they would fix this issue.

**Comment by jimmac** [comment]
New layout is in place.
