### ISSUE TITLE
Flathub.org blue is different to flatpak.org

### ISSUE THREAD

**Issue by ahayzen** [flathub/flathub.org#29]
Flatpak.org uses `#4a90d9`
Flathub.org uses `#4a86cf`

The designs (eg [0]) appear to use `#4a90d9` so looks like flathub.org is using the wrong blue ?

Note: this also affects the beta site.

0 - https://github.com/flatpak-design-team/flatpak-website-mockups/blob/master/flathub.org.png

**Comment by allanday** [comment]
I wouldn't follow the mockups - I didn't give much thought to which colours I was using! I agree that it would be good to use the same shade on both websites though. :)

**Comment by jimmac** [comment]
$key_color: #4a90d9; 

is being used for both site. I'm guessing we fixed it in the meantime :)
