### ISSUE TITLE
"Submit an app" link is broken

### ISSUE THREAD

**Issue by ahayzen** [flathub/flathub.org#31]
What happened:
1) Navigate to https://flathub.org/
2) Notice the "Submit an app" link at the top, click on it
3) Notice that you have ended up at the root of the wiki

What I expected to happen:
At step 3 to be taken to the app submission guidelines page.

The link on flathub.org is pointing to https://github.com/flathub/flathub/wiki/Package-Guidelines it appears this should be to https://github.com/flathub/flathub/wiki/App-Submission ?

Note: beta.flathub.org has a "Publish your app" link, which is also pointing to the same page.

**Comment by allanday** [comment]
There's a fix already committed, but we're having issues updating the live site.

**Comment by allanday** [comment]
We finally got the updates deployed, so this should be fixed.
