### ISSUE TITLE
Apps link is relative on the apps page

### ISSUE THREAD

**Issue by cassidyjames** [flathub/flathub.org#33]
1. Go to https://flathub.org/apps/
2. Click the "Browse apps" navigation link

**Expected:** You don't go anywhere since you're already on the apps page

**Actual:** You are taken to https://flathub.org/apps/apps

**Comment by allanday** [comment]
Probably caused by commit 7262cdc2f.

**Comment by jimmac** [comment]
I wouldn't say it's caused by it, quite the contrary, but the fix isn't deployed.

**Comment by jimmac** [comment]
We no longer expose all apps!

**Comment by zmoshansky** [comment]
@jimmac How does one browse what Flatpak apps are available? Just browsing `data/appstream.json`?

**Comment by jimmac** [comment]
@zmoshansky  https://beta.flathub.org
