### ISSUE TITLE
Broken https://flathub.org/apps/

### ISSUE THREAD

**Issue by jgarciao** [flathub/flathub.org#39]
Since last change this page shows app icons immense. If the page is not used anymore it should be removed and add a redirect to home (there are a lot of links pointing here)

![screenshot-2018-3-20 applications hosted on flathub](https://user-images.githubusercontent.com/66894/37650401-1d396bf2-2c35-11e8-976e-f72f9120c3d0.png)

**Comment by michaelbull** [comment]
There's also no link to the `flathub.org/apps` page on the frontpage anymore, so I don't see how anybody can view the full app catalog anymore. Is there meant to be a replacement page?

**Comment by allanday** [comment]
> Is there meant to be a replacement page?

No, there isn't - it isn't practical to list every app using a static site. The full catalogue will be browsable with [the new site](https://github.com/jgarciao/linux-store-frontend/) when it's ready.

**Comment by michaelbull** [comment]
Ah ok, I'm glad there's definitely a replacement for a full listing of all available apps even if it isn't part of this repository, thanks @allanday.

**Comment by jimmac** [comment]
The /apps > / redirect addresses this in the short term.
