### ISSUE TITLE
issues with the black footer

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/flathub.org#41]
The black footer at the bottom of flathub.org has only three links, which are weirdly spaced out: twitter, home and 'submit an app'. The first is useful, the second just scrolls back to the top (does that really deserve a button?) and the third is a duplicate of the link in the header.

**Comment by jimmac** [comment]
The layout is definitely not working for small number of items, but if we add an about page (issue #40), we might have a reasonable footer with the few items left aligned / compact. What do you think, Allan?

**Comment by allanday** [comment]
> What do you think, Allan?

The current site is a placeholder, so let's not invest too much time on it. Whatever's easiest!

**Comment by allanday** [comment]
I just checked this again, 4 links isn't super but it seems fine to be going on with.

**Comment by jimmac** [comment]
Feel free to reopen if it irks you more than the designers, Matthias ;)
