### ISSUE TITLE
[Beta] Invalid screenshots show as empty images

### ISSUE THREAD

**Issue by dsboger-zz** [flathub/flathub.org#44]
[FMIT](https://beta.flathub.org/apps/details/io.github.gillesdegottex.FMIT) has a couple of too-small-for-appstream screenshots that flathub naturally discards. The issue is that in the app details page, the carousel still keeps empty placeholders for the discarded screenshots.

![image](https://user-images.githubusercontent.com/2356842/37831410-28cfd5cc-2e84-11e8-88f6-e4f195416920.png)

**Comment by TingPing** [comment]
Please report that against this repo: https://github.com/jgarciao/linux-store-frontend/issues
