### ISSUE TITLE
Visited install link buttons change colour

### ISSUE THREAD

**Issue by ahayzen** [flathub/flathub.org#46]
Not sure if this is intentional, but it looks a bit strange.

What happened
1) Navigate for flathub.org
2) Scroll down to the list of apps
3) Notice that all the install buttons have the same colour text
4) Click "Install" for one of the applications and allow the flatpakref to be downloaded and opened
5) Refresh the webpage
6) Notice that the text of the install link has changed colour as the link it is pointing to has been "visited" - as shown in the screenshot below ones I have clicked have changed to a light blue

![screenshot from 2018-03-23 21-52-44](https://user-images.githubusercontent.com/3669750/37854946-ee271352-2ee4-11e8-9783-38b3b6e50b9d.png)

Personally, it feels like the text colour should remain static.

**Comment by jimmac** [comment]
Thanks for spotting.
