### ISSUE TITLE
How to browse flathub website for ALL apps?

### ISSUE THREAD

**Issue by asqwerth** [flathub/flathub.org#48]
The new layout of Flathub's website displays a few selected apps, but gives no way to search/browse the whole list of Flatpak packages.  Previously the format allowed you to do so.  I tried Firefox and Google Chrome last night and searched for a way in to no avail.

As I was on a distro that does not integrate flatpak search into their graphical package manager, I can't use that, so ended up having to do keyword searches in the terminal, which is very inconvenient.

**Comment by allanday** [comment]
We're working on a new site that will allow that. You can try it at http://beta.flathub.org/.

**Comment by jurf** [comment]
We should mention (and maybe link) that, to prevent the unnecessary confusion.

**Comment by asqwerth** [comment]
Much obliged!
