### ISSUE TITLE
Document requirement to use repository + local application

### ISSUE THREAD

**Issue by benzea** [flathub/flathub.org#50]
So, I tried to install a single flatpak, and I just knew that flathub was the place to start.

My navigation went along the lines of:
 0. Look in gnome-software, figure no Flatpaks were available
 1. Go to https://flathub.org
 2. Look for the link of all applications, not just featured
 3. Give up on 2.
 4. Click "Quick Setup"
 5. Click Fedora
 6. Then, wrongly clicked on "install some apps", wondering why I am back
 7. Go back
 8. Install the repo file
 9. Click on "install some apps"
10. Again, wonder how I can find all applications
11. Figure that gnome-software should work at this point
12. Use gnome-software to install the flatpak I wanted
13. (which then continued to crash, but that is a different matter)

It seems to me that the website navigation is designed around having a full list of all Flatpaks available, but this has changed and the navigation has not been updated.

My current suggestions would be:
 1. Add page documenting methods of installing applications locally (gnome-software, flatpak command line client).
 2. Point "Install Applications" there
 3. Add link underneath the "Featured applications" pointing towards the documentation.

**Comment by TingPing** [comment]
Handled by #49

**Comment by allanday** [comment]
> Add page documenting methods of installing applications locally (gnome-software, flatpak command line client).

The text on the home page was suppose to communicate this, but it's probably not prominent or detailed enough. A separate page with more details could be a good improvement.

**Comment by benzea** [comment]
The text has an extremely low visibility and people just don't read blurbs like that most of the time.

**Comment by benzea** [comment]
Also, it does look like an explanation of what flatpak is, rather than instructions. Instructions like that should be better *below* the list of featured applications rather than above it.
