### ISSUE TITLE
add sponsors and supporters

### ISSUE THREAD

**Issue by ramcq** [flathub/flathub.org#7]
It'd be great if the webpage could conspicuously thank/acknowledge and link to our corporate sponsors:
 * Codethink
 * Mythic Beasts
 * Scaleway

And perhaps on a more detailed page, also list out our individual supporters who helped with the fundraise:
  Alex Larsson
  Andreas Nilsson
  Arun Raghavan
  Bartłomiej Piotrowski
  Christian Hegert
  Christopher Halse Rogers
  Cosimo Cecchi
  Emmanuele Bassi
  G Stavracas Neto
  Jakub Steiner
  James Shubin
  Joaquim Rocha
  Jorge García Oncins
  Lubomír Sedlář
  Nathan Dyer
  Nick Richards
  Mario Sanchez Prada
  Matthias Clasen
  Michael Doherty
  Zach Oglesby

**Comment by ramcq** [comment]
https://www.codethink.co.uk/
https://www.mythic-beasts.com/
https://www.scaleway.com/

**Comment by nedrichards** [comment]
@allanday I know you've been doing some redesigning here. May be out of scope for your current efforts though.

**Comment by allanday** [comment]
> @allanday I know you've been doing some redesigning here. May be out of scope for your current efforts though.

I agree that we ought to thank our sponsors somewhere. Maybe if we have a nice about page...

**Comment by allanday** [comment]
I put the list of sponsors on the [design for the new about page](https://raw.githubusercontent.com/flatpak-design-team/flatpak-website-mockups/master/flathub-wires.png).

**Comment by allanday** [comment]
The list is in the redesign that's being implemented in the new-layout-2018 branch.

**Comment by jimmac** [comment]
The about page is in.
